### ISSUE TITLE
no update now?

### ISSUE THREAD

**Issue by cshaaa** [evemuproject/evemu_server#119]
if the code is not updated now?

**Comment by zombu2** [comment]
would you like some fries with that order ?

**Comment by cshaaa** [comment]
@zombu2 sorry,My English is poor,so could give some simple words about "would you like some fries with that order ?"

thank you!

**Comment by zombu2** [comment]
sure you can have fries ,potato wedges or fries with skin on em we also have ketchup mayonnaise  and if you really adventures you can have mustard on them.
sometimes they also great with some sweet and sour or BBQ sauce

**Comment by cshaaa** [comment]
@zombu2 Are you talking about food?

**Comment by zombu2** [comment]
you don't like fries huh?

**Comment by cshaaa** [comment]
@zombu2 yes,I like fries very much.But,but it 's so strange talking about fries here?ahaha!
