### ISSUE TITLE
I cannot enter into the website "http://www.evemu.org"

### ISSUE THREAD

**Issue by cshaaa** [evemuproject/evemu_server#121]
what's the matter?
and who can tell me how to compile a new eveserver?
sorry for my poor english.

**Comment by Reve** [comment]
try http://wiki.evemu.net

**Comment by exmex** [comment]
I've restored an older version of the wiki due to bots altering the content.
	{{NavBar|1|HOME}}
	
	{| cellspacing="0" align="left" style="width: 100%; height:50px; font-weight: normal; border:0px;"
	! style="border:1px solid #FFF;height: 50px; width: 70%; background:#FFFFFF; font-size:18px; font-weight:bold; color:#000000; padding:5px;" | 
	Welcome to [[Image:Evemulogo.png|200px|EVEmu]] the ONLY EVE Online Emulator!
	|-
	|}
	
	[[File:evemu_banner_erebus_vs_leviathan.png|right|480px]]
	Thanks for visiting our wiki.  This is the main page for our project and we're happy you stopped by to see what we're doing.
	
	'''EVEmu''' is an EVE Online Server Emulator that is a 100% open-source home-grown server written in C++, compiled for Windows 32/64 bit and Linux 32/64 bit environments.  The Server Emulator has been in development by a core handful of people who appear now and then for over 7 years.  We have more going on than the Server Emulator, see our [[EVEmu Developers Hub#Projects|projects page]] for a complete listing of what we've worked on.
	
	Currently, EVEmu supports the EVE Online '''[[:Category:Crucible|Crucible]] 1.6.5''' client and for the foreseeable future, we're staying with that client.  See the '''[[Server Status (Crucible)|Crucible Project Status]]''' page to see what we have implemented and what still needs to be worked on.  Our developers keep an eye on what EVE Online is doing from release to release and from time to time, consider the risk versus reward of upgrading to one of the more recent versions.
	
	If you like EVE Online and you are a C++ or C# programmer, we need you!  We are always in need of good, seasoned C++ developers for the [[:Category:Crucible|Main Server Emulator software]] and we could use some C# programmers for our [[EVEmu Control Panel]] program.  We also have a work-in-progress [[:Category:EVEmu Web Portal|Web Portal]] that always needs some experienced hands in PHP/HTML.
	
	EVEmu is a learning project as well.  Even if you are not a seasoned programmer and just want to learn, everyone is welcome to join us in [[EVEmu Connect#IRC EVEmu|IRC]] conversations and [[EVEmu Connect#Teamspeak|Teamspeak]] conversations, then [[Getting Started|get started learning the server codebase]] while you learn C++ from some [[Getting Started#Getting Started|tutorials]] and from our experienced programmers right alongside us.
	{{-}}
	{{-}}
	
	----
	For quick navigation to the most popular important areas of our websites, check out these helpful links and our left sidebar has more:
	
	'''New Users!'''
	* [[EVEmu Connect|Connect with us via IRC, Teamspeak, Forums]]
	* [[Quick Start Guide]] - Go here to get started with EVEmu so you can check it out pronto!
	{{-}}
	
	'''Developers!'''
	* [[EVEmu Developers Hub|Developer Central]] - Learn how EVEmu is an EVE Online Server Emulator and how you can help
	* [[Recent Project Activity]] - Here's what's been going on lately
	----
	{{-}}
	
	Here are what some of the people who've stopped by have said about our project:
	
	"Well, I'm flying around in 1.6.4 with evemu and, for the current state of development, it's working pretty damn well."
	"Great work devs."
	.... and then I LOL'd -- Aknor
	
	"[17:30] <@M4ksiu> pure awesomeness"
	
	"[08:35] <+B3N4K-WIN> Well at first i was reading forums and then someone there said something about private servers.
	So i was googling about private servers but didn't find anything.  And then on like 10th google results page there
	was evemu git link and i was like "WOW!! I thought it's impossible to make emulator! How did they do that?!"...
	And 2 hours later i was flying in scam-free Jita :)"
	
	
	Finally, thank you for visiting our site, if there is something you cannot find, ask us in [[EVEmu Connect|IRC or Teamspeak]], try the [[Special:Search|site search]], or peruse our comprehensive navigation panel below.
	
	-- The EVEmu Team
	
	
	{| width="100%" cellpadding="6" style="border-collapse: collapse;"
	|width="20%" style="background-color: lightgreen; font-weight: bold; text-align:center;border-style:solid;border-width: 1px;border-color: #AAA;"| Server Projects
	|width="20%" style="background-color: lightgreen; font-weight: bold; text-align:center;border-style:solid;border-width: 1px;border-color: #AAA;"| EVEmu Documentation
	|width="25%" style="background-color: lightgreen; font-weight: bold; text-align:center;border-style:solid;border-width: 1px;border-color: #AAA;"| Server Administrators
	|width="33%" style="background-color: lightgreen; font-weight: bold; text-align:center;border-style:solid;border-width: 1px;border-color: #AAA;"| Developers
	|-style="border-style:solid;border-width: 1px;border-color: #AAA;"
	|valign="top"| {{:Main_Page/Server_Projects_Links}}
	|valign="top"| {{:Main_Page/EVEmu_Documentation_Links}}
	|valign="top"| {{:Main_Page/Admin_Links}}
	|valign="top"| {{:Main_Page/Developer_Links}}
	|}
	
	{{Legal}}

**Comment by waliworld** [comment]
Lost images too, was it a directed attack?

**Comment by exmex** [comment]
I don't know but the page got replaced with cyrillic.. (Polnish?)

http://wiki.evemu.net/index.php?title=Main_Page&oldid=1000157

**Comment by VizanArkonin** [comment]
There was a couple mirrors, but they seem to be down now too.
I don't have a web-server-friendly version of the wiki, just the scraped local copy of wiki and forums.
If anyone need it - https://yadi.sk/d/HsyHhoXFmJDzV

Still, that might need some updates, because instructions are really out of date. Aknor wanted to move the whole wiki to the github, but no one started it yet.

**Comment by exmex** [comment]
It seems like EvEmu is very out of date in terms of information :smile:

Thanks for the scraped version though :+1:

**Comment by kingtiger01** [comment]
looks like Revision 781 was the last good one. (http://wiki.evemu.net/index.php?title=Main_Page&oldid=781)

What the hell is going on, on your guys end?

**Comment by VizanArkonin** [comment]
wiki.evemu.net is just a mirror. Unfortunately, it did not had the registration blocked so it got invaded by the bots.
Official forums/wiki on .org domain are gone. For good or not - not quite clear. The folk who was maintaining them have gone silent again.

**Comment by zhyrohaad** [comment]
@kingtiger01.   0.o.  Not much.  No one is interested in helping.  What the hell is going on at your end?
