### ISSUE TITLE
Is EveMu project dead?

### ISSUE THREAD

**Issue by ghost** [evemuproject/evemu_server#123]
Hi,

just wanted to know if the EveMu project is officially dead?
The webpage seems to be down including forums, etc.

Is there a way to stay in touch with the developers?
Is a new community around the project planned?

Thanks!

Best regards

**Comment by VizanArkonin** [comment]
Hi mate.

Nope, we're still around. Letargic sleep was pretty normal for the whole time, so it's ok.
No one knows what happened to the forums/wiki, as the guy who were hosting it wasn't been around for like a year. or even more.

We still have our IRC channel operable, and above that, pretty active lately. Feel free to drop by the
irc.evemu.net:6667 and #evemu channel.
If you meant the new forums/wiki and such - that's actually a good question. We've got a wiki mirror + some stuff stored in waybackmachine, but no exact plans were made yet.

Cheers!
DaVinci.

**Comment by waliworld** [comment]
@VizanArkonin the irc server seems down, or is it just me?

**Comment by AlauraLeafLoveless** [comment]
Always look around Waliworld, these is a discord up, https://discord.gg/0vF5ux3158sQFYDH

**Comment by zhyrohaad** [comment]
with the update of my major rewrite, this project is not dead.
