### ISSUE TITLE
How did you get detail information about eve client

### ISSUE THREAD

**Issue by crazyevent** [evemuproject/evemu_server#131]
I want to be a developer of evemu project, but I have no idea how to crack eve's network protocol or resource file format.

**Comment by VizanArkonin** [comment]
well, can't tell about the network protocol, but client have a scripting module, that processes the incoming/outcoming packets (script/compiled.code).
It is written on Python, so you can de-compile it and get the approx. sources that you can use to find the packet structure client expects.

**Comment by zhyrohaad** [comment]
there are also network packet sniffers that some have used to get data sent to and from the client.  i havent gotten any of them to work for me, so i cant help there.
