### ISSUE TITLE
Error compiling with clang on osx

### ISSUE THREAD

**Issue by cbacon93** [evemuproject/evemu_server#138]
Hi,

i tried to compile the evemu server on my mac with clang but i got the following error:

    cd /Users/marcel/Documents/Coding/evemu_build/src/eve-core && /usr/bin/g++   -DHAVE_CONFIG_H -I/Users/marcel/Documents/Coding/evemu_build -I/usr/local/include -I/usr/local/include/mysql -I/Users/marcel/Documents/Coding/evemu_server/dep/gangsta -I/Users/marcel/Documents/Coding/evemu_build/tinyxml -I/opt/local/include -I/Users/marcel/Documents/Coding/evemu_server/src/eve-core -o CMakeFiles/eve-core.dir/eve-compat.cpp.o -c /Users/marcel/Documents/Coding/evemu_server/src/eve-core/eve-compat.cpp
    In file included from /Users/marcel/Documents/Coding/evemu_server/src/eve-core/eve-compat.cpp:26:
    In file included from /Users/marcel/Documents/Coding/evemu_server/src/eve-core/eve-core.h:62:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cassert:20:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:
    /usr/include/unistd.h:600:47: error: redefinition of parameter 'restrict'
    void     swab(const void * __restrict, void * __restrict, ssize_t);
                                              ^
    /usr/include/sys/cdefs.h:209:20: note: expanded from macro '__restrict'
    #define __restrict      restrict
                        ^
    /usr/include/unistd.h:600:28: note: previous declaration is here
    void     swab(const void * __restrict, void * __restrict, ssize_t);
                           ^
    /usr/include/sys/cdefs.h:209:20: note: expanded from macro '__restrict'
    #define __restrict      restrict

Did someone got this error before and knows how to fix it?
Btw: My cmake didn't set the include directories for the precompiled header properly so i had to remove it

**Comment by comet0** [comment]
We do not target OSX or Clang.
