### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by DeusOfAces** [evemuproject/evemu_server#139]
Hi! I am just wondering if there is any possibility to contact the staff? E-mail, anything?

**Comment by VizanArkonin** [comment]
Hi mate.
As forums are down again, the best bet will be our IRC channel.
irc.evemu.net:6667

**Comment by DeusOfAces** [comment]
Ah I see, I joined the IRC, but can't find any channels?

On mån, jan 25, 2016 at 12:24 em, VizanArkonin < notifications@github.com [notifications@github.com] > wrote:
Hi mate.
As forums are down again, the best bet will be our IRC channel.
irc.evemu.net:6667

—
Reply to this email directly or view it on GitHub
[https://github.com/evemuproject/evemu_server/issues/139#issuecomment-174477178] .[https://github.com/notifications/beacon/AJGPEYiXytMInAV9TQpdjx8ltIJbx8H_ks5pdf0XgaJpZM4HLfGE.gif]

**Comment by comet0** [comment]
#evemu channel
On 25 Jan 2016 11:47, DeusOfAces <notifications@github.com> wrote:Ah I see, I joined the IRC, but can't find any channels?

On mån, jan 25, 2016 at 12:24 em, VizanArkonin < notifications@github.com [notifications@github.com] > wrote:
Hi mate.
As forums are down again, the best bet will be our IRC channel.
irc.evemu.net:6667

—
Reply to this email directly or view it on GitHub
[https://github.com/evemuproject/evemu_server/issues/139#issuecomment-174477178] .[https://github.com/notifications/beacon/AJGPEYiXytMInAV9TQpdjx8ltIJbx8H_ks5pdf0XgaJpZM4HLfGE.gif]

**Comment by zhyrohaad** [comment]
To what "staff" are you referring?  We don't really have anything like that.  There are a few on irc that can help with the most common problems, but no real directors.  Reve is the most senior member we have, but like the others, he's not very active here lately.  If/when you get on irc, please be patient....no one is just sitting there waiting for someone to talk.  
Thanks for your interest.

**Comment by brokentechnology** [comment]
Looks like the domain expired, I was going to hop on IRC to offer dedicated web space for free (I operate a co-located server at my place of employment)

**Comment by brokentechnology** [comment]
Weird, when I try to load evemu.net via irc it times out, the web page shows expired, however whois says expires next year.

**Comment by VizanArkonin** [comment]
yep, both .net wiki and IRC went down.
Gonna talk to allan - got to figure proper comms out.

**Comment by MMOEmulators** [comment]
Anyone get a hold of anyone yet? I'm worried this project has vanished from the face of the interwebs for good. I am interested in offering my services once again for a stable, permanent web/wiki/irc/project site and/or administration, but have no way to contact anyone but this...

If someone knows "allan", the latest committer, or has contact with whomever holds the forum/wiki hostage, please have them drop me an email at mmoemulators@gmail.com

Very serious about free hosting for life. But someone needs to let me. ~JA

**Comment by VizanArkonin** [comment]
Hey mate.
Well, we're kind of still around, just went silent again (not out first time).
Allan haz some RL stuff to rule out in the next few weeks, so the only place you can possibly leave him a note and talk with is our current [Discord channel](https://discord.gg/SqFNdwb).

Cheers!

**Comment by zhyrohaad** [comment]
there are other places that give our contact info.
this is closed.
