### ISSUE TITLE
Need Advice with error C1189 compiling with MVSC++2013.

### ISSUE THREAD

**Issue by RazMan83** [evemuproject/evemu_server#141]
looking at the wiki instructions for compiling the files from evemu_server i get past the cmake part np. when i get into using MSC++2013 and i get some errors the refuses to build files.

Errors 11
Warnings 17

========== Rebuild All: 8 succeeded, 6 failed, 3 skipped ==========

error C1189: #error : ERROR: You must use a GNU Compiler.
error MSB6006: "cmd.exe" exited with code 9009

most of it is pointing towards using a GNU Compiler no clue what this is im realy new to this. i wanted to try this out to help me learn a thing or two about coding and databases with mysql.

if i can get this working and you are still working on this code id like to jump on board once im up to par with the basics.

as for updating the game to use newer models and graphics ive made some progress using the older evemu_server.exe and eve crucible client.

**Comment by NickTaylor-** [comment]
Could you post the entire build log to Gist or some other paste site?

**Comment by RazMan83** [comment]
do you mean the log i get after i try building the files? like the errors etc , if so theres a log i think for every type 

eve-collector
eve-common
eve-core
eve-server
eve-test
eve-tool
eve-xmlpktgen
etc is there a place that shows alog for all issues in one single file ?
if so were would i find and would i post it on here or would i upload the file ?
i belive some of my probblems are related to the GnuWin32 folder looks like im missing somthing.
the other one im getting is C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009. the rest of my issues are warnings but i think if those to errores was fixed then the warning would go away.

**Comment by RazMan83** [comment]
is it called ALL_BUILDLOG ? ive found one that shows a lot of information including errors but its way to much info to post on here im gonna go back and try building it again and get a smaller error log for you. im thinking most of this is to do with GnuWin32 folder missing files its saying i need to use a GNU compiler this is the one thats popping up alot. i think im missing something.

**Comment by RazMan83** [comment]
ive tracked an error in cmake thats saying build failed goto here and dl the logs see what you make of them.

CMakeError.log
https://mega.nz/#!Lsp0yJZJ!WopKVu4qo-JwMNwuAWzTCGsKTz8kXsIS1dwbwYJYyog

CMakeOutput.log
https://mega.nz/#!b8Z1waJJ!gJQEi3YC6W6JpZycX4vIoV9C-sfKkkiVLsDeKbl9byI

its looking like the same issue as i have with MVS2013 same error code btw when i try building with cmake it looks for files some it says found others it say not found thx in advance.

**Comment by RazMan83** [comment]
OK got in down to 2 main things 1st _mingw.h i think my version is to low or installed incorrectly 
and 2nd is the cmd.exe now im not sure if this is the git cmd or windows cmd.exe ether way it fails ive backed up my system and about to do a full format. ive tried reinstalling what i need with no joy my system could do with a format been putting it off for along time. ive learnt alot trying to debug my probblem. ill post back soon.

**Comment by eve-moo** [comment]
I use Linux and gcc so I'm not to familiar with windows but I did recently see something about there being an "old" version of minggw that uses a file mingw32-make that won't work on newer stuff.  Instead you need to make sure you use the make.exe in the mingw/bin directory.  Don't know if that'll help but it's all I got right now.

**Comment by zhyrohaad** [comment]
there were no further replies or updates to this issue.
any new problems like this should open a new bug report.
