### ISSUE TITLE
eve-collector

### ISSUE THREAD

**Issue by eve-moo** [evemuproject/evemu_server#144]
eve-collector... What is it?  What does it do?  Does it have any purpose?  It looks like it has not been touched since 2009.  Is this something we could get rid of?  Or at least remove from the build tree?

**Comment by comet0** [comment]
But eve-collector is not built, it does not have a cmake file (well it does but it is empty...)
As for what it does, it appears to be an old packet capture mechanism.
-cometo

**Comment by zhyrohaad** [comment]
it is a server-side packet capture-and-log system written by Zhur while developing the server's packet system.  it is no longer used, and hasnt been in quite a while.
it is still here for historical/archive purposes, and no longer needed in the build tree.

**Comment by zhyrohaad** [comment]
i forgot to close this with my previous comment
