### ISSUE TITLE
Communication needed.

### ISSUE THREAD

**Issue by Alauraa** [evemuproject/evemu_server#146]
Seeing as the irc is down, I don't know for how long, We need to have a secondary backup, in other words, I made a discord for Evemu and we have a slack up for evemu as well. I don't know how to find it but we do have a slack for it. But as stated, I made a discord, can be temporarily or can be permanent. Up to Allan and them to decide. 

Here is the invite code: https://discord.gg/0vF5ux3158sQFYDH

Probably not the best place for this, but its as good as i can get it seeing as i have yet to get a email for the forums.

**Comment by zhyrohaad** [comment]
with James' recent updates, there are multiple places to find our contact info.
this is closed
