### ISSUE TITLE
EVEmu Wiki migration to wikia.com

### ISSUE THREAD

**Issue by gholol** [evemuproject/evemu_server#150]
Hi

We all know what happened to evemu.org (I mean, it's down). I'm trying to migrate our wiki assets (or rather what's left of them) into the wikia.com 

http://evemu.wikia.com

The actual project status (IMO the most important page) is available here, so you can check out what's working and what doesn't.
http://evemu.wikia.com/wiki/Crucible_Project_Status

It needs updating because a lot have changed since october 2014 (or at least I hope so) So if anyone is willing to re-check and make changes - let me know!

There's A LOT of work to do in order to make this wiki readable, so it will take me at least few days

**Comment by zhyrohaad** [comment]
hey gholol
looks good.
the status page is accurate.  it's true.  not much has changed since Oct14.
if you're interested in moving the other saved info we have (non-formated...needs LOTS of editing to be readable), then lemme know and i'll send ya a link.
thanks

**Comment by gholol** [comment]
Any time! If you have anything else,  please send me the link.

**Comment by zhyrohaad** [comment]
we are currently using discord, as the irc and forums are no longer online.
alaura made a page specifically for your wiki work. 
this is the invite to that page..  https://discord.gg/0vF5ux3158veosX4
here is the invite to main page.  https://discord.gg/0vF5ux3158sR2a48

i'll find that link to the old data and put it up here.

**Comment by tostercx** [comment]
Hey, does anyone have a copy of the page 'EVE Protocol'? Couldn't find it anywhere. They seem to be using some kind of serialized python objects or at least it seems so...

**Comment by sau226** [comment]
@gholol I took over the Wikia site since it appeared neglected. If a collaborator on this project wants to take a more active role in wiki management feel free to ping me,

**Comment by zhyrohaad** [comment]
didnt know that wiki was still active.

**Comment by jdhirst** [comment]
This can be closed since the new site can be updated via git pull requests here: https://github.com/jdhirst/evemu_web
I will move that repo into evemuproject once it is converted into an org.
