### ISSUE TITLE
Cmake: Lua51 version not detected

### ISSUE THREAD

**Issue by EndlessEden** [evemuproject/evemu_server#160]
OS: Linux
Distribution: Archlinux
Lua51 version: 5.1.5 (/usr/lib/liblua5.1.so -> liblua5.1.so.5.1.5)
------
`Could NOT find Lua51: Found unsuitable version "", but required is at least "5.1" (found /usr/lib/liblua5.1.so;/usr/lib/libm.so)`
------

liblua5.1 is currently installed (https://www.archlinux.org/packages/extra/x86_64/lua51/) - But its version is not extracted. Either cmake is not following the symlink to the file, or is using some depreciated method of extracting it.

**Comment by zhyrohaad** [comment]
lua was an idea years ago for a scripting language to enable server-side scripting for server scripts.
this was never implemented, nor have i personally found a use for it.
it should be removed.

**Comment by EndlessEden** [comment]
i would recommend setting it as a optional dependancy. enable it via a switch. 
Even if its not currently impletmented, i personally think it would be useful in the future.

**Comment by zhyrohaad** [comment]
that would be fine.
you interested in doing that?

**Comment by jdhirst** [comment]
I have removed it in my pull request. If it will actually be used, that is when it should be added as a dependency in my opinion.

It can always be readded if and when code that uses it is added to the server.
