### ISSUE TITLE
Information about additional bugs not in this list.   Those testing this branch should read.

### ISSUE THREAD

**Issue by zhyrohaad** [evemuproject/evemu_server#173]
As this code is derived from Alasiya-EvE, the Alasiya buglist is relevant here also.
there may also be other bugs or problems inherent with integrating the large amount of code that was used to update EvEmu official.

Alasiya-EvE buglist can be found here.....  [https://github.com/zhyrohaad/AlasiyaEvE/issues](url)

**Comment by jdhirst** [comment]
Issue moved to new repo. Please close.
