### ISSUE TITLE
Shrinking the repository

### ISSUE THREAD

**Issue by bobekjan** [evemuproject/evemu_server#3]
See also http://forum.evemu.org/viewtopic.php?f=7&t=721.

As promised, I tried using `git filter-branch` to make the repository smaller. I was successful; however, it turns out that the removed stuff (_boost_, _mysql_, _zlib_) saves us about 4 megs of space, which isn't that much (the repo has ~32 MB atm).
I investigated further and found out that we could save additional 12 (!) megabytes if we removed _utils/playertools_, making the repository only ~16 MB (half of the original value!).

This is disk usage of current checked-out tree (that is, with _boost_, _mysql_ and _zlib_ removed), ordered from the smallest:

```
36K   cmake
84K   doc
2.1M  include
3.4M  src
5.1M  dep
25M   sql
26M   utils
```

It's apparent that removing _utils/playertools_ could save us some serious megs (the directory _utils_ itself holds hardly anything).

So, any thoughts?

**Comment by jdhirst** [comment]
I think we can close this. I did a bunch of work on shrinking the repo, compressing sql files, getting rid of unused files, etc.
