### ISSUE TITLE
Create new database table to link Ship typeIDs to Wreck typeIDs

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#33]
ASSIGNED TO:  kingtiger01

TASK:

PART ONE:
We need to create a new database table, called "shipTypeWrecks", with structure of typeID as INT and wreckTypeID as INT.  The table needs no other fields.  The goal here is to choose a typeID from invTypes table for a wreck and match that to all the appropriate ship typeIDs.  This is a daunting task as there are 376 player operable ships as well as the scores of NPC ships, all of which have wreck types.  The task can be made a bit less daunting by realizing that just about every wreck will link to multiple typeIDs.  The time consuming part will be simply filtering the typeIDs to discover which are linked to the same wreck, then the table can be constructed from the data.

If it is easier to do, data can be entered into our wiki at http://wiki.evemu.org.

When this part is done, pass off the Issue to AknorJaden for PART TWO.

PART TWO:
We need to create the code in the server to pull the data from the new table when a ship is created or spawned and load the wreckID for that ship/NPC typeID.  Code also needs to be created in Damage.cpp to properly spawn the object for the wreckID

**Comment by zhyrohaad** [comment]
this was created, coded, and implemented, but this issue wasnt closed.
