### ISSUE TITLE
SQL dumps in ofic-updates create table dulpicates with different names (even more on linux)

### ISSUE THREAD

**Issue by positron96** [evemuproject/evemu_server#42]
I noticed that sql dumps from bulkdata and cache files create tables with similar contents but different names (and naming convertions) than official CCP tables. I noticed these:

dgmeffects ->(should be) dgmEffects
dgmattribs -> dgmTypeAttributes
bpTypes -> invBlueprintTypes
certificateRelationShips -> crtRelationships
graphics -> eveGraphics
icons -> eveIcons

The problem is, sometimes both tables are used in code (e.g. graphics in https://github.com/evemuproject/evemu_server/blob/master/src/eve-server/cache/ObjCacheDB.cpp#L701 and eveGraphics in https://github.com/evemuproject/evemu_server/blob/master/src/eve-server/config/ConfigDB.cpp#L215, I also noticed dgmattribs and dgmTypeAttributes being used)

Why is it so? Is it really needed to duplicate tables with similar content, and break eve naming convention? If not, this can and should be fixed (and I almost started doing it, but then noticed that these wrongly named tables are used) or it will lead to confision and other problems. I guess noone really needs two tables with same purpose, and if one does, let's rename them to reduce chaos. (E.g rename dgmattribs to dgmAttributeTypesFull or dgmAttributeTypes2)

PS, Linux filesystem is usually case-sensitive, and so are names of tables in mysql (http://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html).
Some sql dumps in ofic-updates folder are spelt in lowercasae (I noticed crpNPCDivisions and fixed it in https://github.com/positron96/evemu_server/commit/e6f1ed2984ee1302621363cafb770b86fd49240f and https://github.com/positron96/evemu_server/commit/50b543a49049dcb617b6768734adab67ad0dc8c7)

**Comment by zhyrohaad** [comment]
this has been fixed in major rewrite
