### ISSUE TITLE
EVEmu Control Panel and other tools don't know what type of database is being accessed

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#48]
PROBLEM:

EVEmu Control Panel, the Web Portal, etc should all be able to query the database they are connected to in order to use appropriate queries and present appropriate options and data to the user based on which type of database is identified, be it Apocrypha, Incursion, Crucible, or beyond as CCP keeps changing database data and structure.

NEED PROPOSALS:
My proposal would be a new database table, called say 'system' perhaps, that would contain just one row and a bunch of columns, such as "client version", "macho version", "client version name", "evemu server version", etc

Other proposals are welcome!
- Aknor

**Comment by zhyrohaad** [comment]
as there is no updates on this, and it seems the control panel is no longer functional, this is being closed.
if this problem arises again, a new bug report should be filed.
