### ISSUE TITLE
Make all Logging systems flush data to files during server runtime

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#52]
PROBLEM:
When the server crashes, any logs that are currently open by the existing logging system(s) will not have been written to the file on the hard drive and therefore will be empty when viewed after the crash.  Something needs to be done such that logging data is written to files while the server is running such that the logs are not empty in the event the server does crash.

STEPS TO REPRODUCE:
not applicable, this is an Enhancement

WORKAROUND:
Not sure there is a workaround, heh, don't let your server crash else the logs will be empty XD

PROPOSED SOLUTIONS:
(1)  Open log file, write log data, close log file -- every time there is log data to write, however small.   Problem with this is there will be many file open/close operations when there is a lot of data getting logged per second.
(2)  Implement (1), but use a timer to determine when to close the file then restart the timer and open the file again, so file close/open operations only happen when the timer expires.  Problem with this is that you may lose up to the amount of time the timer runs worth of log data leading up to the server crash.
(3)  Implement a function in the logging system that can let the programmers call to "flush" the log, letting programmers decide how often to flush log data to the file.  The "flush" operation would be nothing more than closing the log file and reopening it.

Any other ideas folks?  If so, just leave them in comments here.

-- Aknor

**Comment by zhyrohaad** [comment]
most of the 'old' log-to-file systems are no longer used.
if this problem arises again, a new bug report should be filed.
