### ISSUE TITLE
Market base prices are WAY too high

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#58]
Now that positron's market fixes are in, we can view and buy items off the market after they've been seeded there in the market_orders table.  The problem with this right now is the base price in the invTypes table for each item is WAY too high.  1,050,000,000,000.00 for a Megathron.  That's just ridiculous.

So, with Xyrtic's help, we have an idea of grabbing data from eve-central.com API server for pricing data for all types using the following query:

http://api.eve-central.com/api/marketstat?typeid=641&typeid=641&regionlimit=10000002

Here, typeid=641 is for Megathron and regionlimit=10000002 is for The Forge region.  We can create a PHP or python script to grab pricing data for all types for each region and make an update SQL file for the market_orders table.

**Comment by zhyrohaad** [comment]
this has been fixed in my major rewrite, but not all data has been updated as of yet.
