### ISSUE TITLE
Ship Fittings loaded after server restart or log-off -> login leave ALL modules Offline

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#64]
PROBLEM:
When fitting modules that go Online, restarting the server and observing the modules fitted to ships prior to the restart show all Offline instead of whatever online/offline state they had prior to the restart.

STEPS TO REPRODUCE:
1. Log into an account and log into the game with a character
2. Fit one or more modules to a ship, then log off
3. Shutdown the server
4. Restart the server and login with your character.  The ship fitting will show all modules in the Offline state

WORKAROUND:
There are no known workarounds for this problem.

PROPOSED SOLUTIONS:
I suspect this has something to do with the Online attribute either not getting properly saved to the database or not properly pulled from the database and updated in the in-memory object for the module when it gets created from the stored fitting.  I am leaning toward the latter since I have observed attribute 2 (online) is set to 1 in the 'entity_attributes' table for such modules.  This must mean that somehow the server is not using that value to update the modules' power states.

**Comment by zhyrohaad** [comment]
this has been fixed in my major rewrite
