### ISSUE TITLE
DogmaIMBound::Handle_GetAllInfo() method is Incomplete in creating the response packet

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#67]
Simply stated, the DogmaIMBound::Handle_GetAllInfo() method in the DogmaIMService.cpp file in the DogmaIMBound class is incomplete.

The "locationInfo" and "shipModifiedCharAttribs" keys in the response dictionary are not filled with anything at the moment.  These should be studied in the server response of the GetAllInfo service call then filled properly with server-side data being requested by the client.

You will need EVE live packet captures, preferrably from Crucible 1.6.5 era in order to figure out what to send back.  Alternatively, if you are brave, you can decompyle the Crucible 1.6.5 client /script/compiled.code file using the python uncompyle2 tool and inspect the python source code to figure out what it wants and reverse engineer what the packet should look like and contain.

**Comment by zhyrohaad** [comment]
this has been updated for proper packet response via my rewrite updates.
`locationInfo` and `shipModifiedCharAttributes` are not used that i can tell.
