### ISSUE TITLE
Creating Corporation with Too-Long name results in SQL Error and NO new Corp created

### ISSUE THREAD

**Issue by evemuproject** [evemuproject/evemu_server#69]
PROBLEM:
When creating a corporation with a name longer than 24 characters (including the word Corporation that is auto-filled by the client), the following error is seen in the server log:  http://pastebin.com/tkcp1azk

Notice the SQL error on the 'reason' field being too long.

STEPS TO REPRODUCE:
1) start server, login with an existing character
2) create a corporation and make sure the length of the corporation name is longer than 24 characters

WORKAROUND:
The only known workaround is to make your corporation name shorter than 25 characters when creating one.  This maximum length of the 'reason' field in the 'market_journal' table is 43 characters and this particular instance exceeded that length, thereby causing the SQL statement to fail.  Stay below that limit and the query will go through.

PROPOSED SOLUTIONS:
We could do one of the following or something else I have not thought of:
1) We really should just write the code that inserts this into 'market_journal' to simply truncate the text going into the 'reason' field to the length expected.  I don't know how we would query the DB to get the maximum length, but for expediency, we could just hard code the length to 43 characters in the server code and truncate text to that length.
2) Add some SQL statement a new file in the sql/ofic-updates folder that will increase the length of the 'reason' field in the 'market_journal' table
3) Shorten the text inserted into the 'reason' field of the 'market_journal' table when a new corporation is created.  Currently, this text is "Creating new corporation:".  This can be shortened to simply "New corp:" instead.

I vote for solution (1) as it is the most elegant and solves the problem the right way.  We should not impose some character limit on corporation names just because of some dumb limit from some other table not wholly related to corporations.

**Comment by zhyrohaad** [comment]
this has been updated/fixed in my major code rewrite.
error messages are now implemented to inform client of problems.
