### ISSUE TITLE
Inefficient Data Storage of Default Attributes of Entity items

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#71]
THE PROBLEM:
Each time an item is created in the EVE universe, the server creates a row in the 'entity' table and creates rows in the 'entity_attributes' and 'entity_default_attributes' tables for the attributes of that item (mass, radius, armor thermal resonance, etc).  Now, the 'entity_attributes' table is for storing the attributes of every unique item instance in the EVE universe and provides a place for holding those attribute values when they are modified by a skill, implant, booster, module, charge, etc.  The 'entity_default_attributes' table holds those same sets of attributes for all unique items but they are NEVER allowed to be modified.  They are default to what was found in the 'dgmTypeAttributes' table.  The problem here is a complete waste of space that I coded up when I expanded the attributes system ahead of working to implement modules and realized it would be quicker to recalculate attribute changes from the default whenever some attribute modifier was added/removed/changed.  So it made sense to maintain an in-memory copy of the default set of attributes in every item object that is loaded in the game when the server is running.  It seemed easiest to modify the AttributeMap class to allow for loading attributes from one of two tables based on whether the AttributeMap was modifiable or read-only (ie default).  The code for AttributeMap does not allow for loading/storing these default attribute sets based on typeID but rather itemID, and that is where space in the Database will be wasted if this is not addressed.

STEPS TO REPRODUCE:
1) log into the game and buy an item off the market or create one using .create <typeID>
2) view the additions to the 'entity_default_attributes' table in the database for your EVEmu server, you'll see that there is a set for each unique itemID found in the 'entity' table whereas it could be stored based only on typeID OR even pulled straight from dgmTypeAttributes table every time an item is loaded from the DB or created

PROPOSED SOLUTION:
At first, I thought it might be best to have AttributeMap just load the attribute set from 'dgmTypeAttributes' every time an item object is loaded/created by the server, however, in my experience of working with items and modules so far, there are a number of attributes that are not present in the list stored in 'dgmTypeAttributes' for each typeID.  Therefore, I think the best solution would be to just modify AttributeMap class so that it loads/stores the default attribute sets based on typeID and not itemID.

**Comment by zhyrohaad** [comment]
the entire attribute system has been rewritten and updated
