### ISSUE TITLE
Missing Item Attributes Require Creation and Assignment of Default Values

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#74]
-- PERPETUAL OPEN ISSUE UNTIL ALL MISSING ATTRIBUTES ARE IDENTIFIED
-- MARK MISSING ATTRIBUTES AS DONE WHEN THEY ARE FOUND AND IMPLEMENTED

Some items may have missing attributes from the list pulled from the 'dgmTypeAttributes' table in the Database and so therefore have to be created manually by the Class Constructor for that Item type.  This Issue is for tracking the work needed to add these missing attributes for various item categories/groups/types and assignment of default values pulled from the 'dgmAttributeTypes' table.  Code in each constructor must test for the existence of these attributes before attempting to add them as some types within groups/categories may not be missing these attributes while others are.

Ships:
- Add 'droneControlDistance' with default value of 20000 (from dgmAttributeTypes ID= 458

MORE TO BE ADDED AS NEEDED

**Comment by cbacon93** [comment]
I frequently get the error message: unable to find attribute: 38 for item ... This is probably the reason that there are no modules on my fresh spawned rookie ship.

**Comment by VizanArkonin** [comment]
Actually, not.
Those attributes define the possible effect the item/skill/implant/ship might have on a ship/module (for instance - Gunnery skill, that gives 2% to turrets RoF per level).
As for rookie ships  - currently, we didn't implemented the fitted rookie ships creation yet, so the stuff appears in the station hangar instead.

Cheers!

**Comment by zhyrohaad** [comment]
this has been fixed via major rewrite
