### ISSUE TITLE
Create or document ability to NOT download deps in CMake Configure

### ISSUE THREAD

**Issue by aknorjaden** [evemuproject/evemu_server#9]
I have a common directory into which I install and link to evemu's dependencies of boost, mysql, and zilb in the old style of doing things and I'd like to keep it that way and not download any deps to be installed into the evemu_server directory.  I'd like a way to tell CMake to not download them and use the ones I have setup instead.

This is because I might have more than one project directory and I dont want multiple copies of each dependency embedded within the dep/ directory.

Please, Bloody.Rabbit, can you help me with this?

Aknor

**Comment by zhyrohaad** [comment]
now that we have resumed work on this project, is this particular item still relevant?

**Comment by jdhirst** [comment]
This is not really relevant since the docs are available here: https://evemu.dev/docs/compiling_from_source/
Additionally, building via Docker makes this completely irrelevant since deps are handled by build container.

I suggest we close this.
